version: "3.8"
services:
    server:
        container_name: server
        image: server:latest
        build: ./server
        restart: always
        ports:
            - "3001:3001"
        environment:
            - PORT=3001
    client:
        container_name: client
        image: client:latest
        restart: always
        build: ./client
        ports:
            - "3000:3000"
        environment:
            - REACT_APP_PROXY=http://server:3001
        depends_on:
            - server
        links:
            - server
